### PR TITLE
fix: check for flushed response headers during proxy request errors

### LINKED ISSUE #86: Response being written after being sent because res.sent is undefined
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.14.1

### Plugin version

2.1.0

### Node.js version

16.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

NA

### Description

When the `request` encounters and error and that error is passed to the callback it is possible to get into a scenario where the response attempts to write after it has already been sent because `res.sent` is `undefined`. This results in an uncaught exception `[ERR_STREAM_WRITE_AFTER_END]: write after end` to be thrown if a response has already been sent.

Looking at the type of `res` argument (`http.ServerResponse`) there isn't an attribute called `sent` so it seems like this we will always get into this conditional [here](https://github.com/fastify/fast-proxy/blob/5fc8676aaa42bda202eee6b22e3a9a8d3b060590/index.js#L89-L102) .

### Steps to Reproduce

Unsure of how to replicate this. 

### Expected Behavior

A check to see if all writeable data has been flushed in order to get into this conditional. Perhaps checking `response.writeableFinished`

### PR DESCRIPTION
**Pull request by jcbain**
Resolves #86 

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ function fastProxy (opts = {}) {
       }
       request(reqParams, (err, response) => {
         if (err) {
-          if (!res.sent) {
+          if (!res.sent || !res.writableFinished) {
```
Comment (q0rban) [inline index.js:91]: It might be helpful to have a comment here to explain these two separate attributes of the `res` and why we are checking both.

Comment (jcbain) [reply index.js]: I like the suggestion and indeed, you are correct. It still would have executed that conditional in that case. I can't speak for `res.sent` but I know that `res.writableFinished` is indeed a boolean. I think it would be best to explicitly check with an or in this case in case `res.sent` is conceptually distinct in some way

**Review by Eomm — APPROVED** [review]

**Review by Uzlopak — COMMENTED** [review]
I have no clue.
