### PR TITLE
fix: strip leading slashes only

### LINKED ISSUE #76: Only match beginning of URL when stripping additional forward slashes
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

2.1.0

### Plugin version

_No response_

### Node.js version

16.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

N/A

### Description

In #42 a scenario was given where a user might be able to perform an SSRF attack by using a specially crafted URL with two leading forward slashes. The implemented fix has the side effect of stripping all double slashes from the entire request URL.

For example, given the following URL:

```
https://chicken.com/duck?redirect_uri=//quack-a-doodle-doo.com
```

The proxy will then strip the additional `/` off of the URL there.

The slash in a query parameter [does not need to be url encoded](https://datatracker.ietf.org/doc/html/rfc3986#section-3.4). 

> The characters slash ("/") and question mark ("?") may represent data within the query component.

If I am understanding the vulnerability originally reported in #42 , it only exists if the `//` is at the beginning of the URL.

What I would like to propose is to only convert `//` if they are at the beginning of the URL.

### Steps to Reproduce

Pass a request to `fast-proxy` with double slashes in the URL, such as `/duck?redirect_uri=//quack-a-doodle-doo.com`.

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by q0rban**
Resolves #76 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by q0rban** [comment]
Added some tests. If you run the tests on master branch, you get this:

```
  1) buildURL
       should not strip double slashes from query parameters:

      AssertionError: expected 'http://localhost/hi?bye=https%3A/exam…' to equal 'http://localhost/hi?bye=https%3A//exa…'
      + expected - actual

      -http://localhost/hi?bye=https%3A/example.com
      +http://localhost/hi?bye=https%3A//example.com

      at Context.<anonymous> (test/10.build-url.test.js:35:25)
      at processImmediate (node:internal/timers:466:21)
```

**Comment by yoosful** [comment]
upvoting, as i'm facing the same issue

File: lib/utils.js [hunk 1]
```diff
@@ -78,7 +78,7 @@ function filterHeaders (headers, filter) {
 
 function buildURL (source = '', reqBase) {
   // issue ref: https://github.com/fastify/fast-proxy/issues/42
-  const cleanSource = source.replace(/\/+/g, '/')
+  const cleanSource = source.replace(/^\/+/g, '/')
```
Comment (Eomm) [inline lib/utils.js:81]: The regexp is no more necessary - it can be converted to be more performant:

https://www.nearform.com/blog/the-secrets-behind-high-performance-with-node-js/

```suggestion
  let i = 0
  while (source[i] === '/') {
    i++
  }
  const cleanSource = '/' + source.substring(i)
```

**Review by Eomm — COMMENTED** [review]
can't re-run the CI, we need a commit

When it will be green LGTM

File: lib/utils.js (hunk 1 above)
Comment (q0rban) [reply lib/utils.js:81]: Clever, I like it. I'll leave it to the maintainers to decide if they'd rather have this or a regex.

Comment (q0rban) [reply lib/utils.js:81]: Oh, you are a maintainer. I'll make the change!

**Comment by q0rban** [comment]
> can't re-run the CI, we need a commit

I pushed a new commit, I need someone to approve the GHA workflow.

**Review by Eomm — APPROVED** [review]

File: lib/utils.js [hunk 2]
```diff
@@ -78,7 +78,11 @@ function filterHeaders (headers, filter) {
 
 function buildURL (source = '', reqBase) {
   // issue ref: https://github.com/fastify/fast-proxy/issues/42
-  const cleanSource = source.replace(/\/+/g, '/')
+  let i = 0
+  while (source[i] === '/') {
+    i++
+  }
```
Comment (jsumners) [inline lib/utils.js:84]:
```suggestion
  while (source[i] === '/') {
    // Skip leading slash characters in the query parameter value,
    // as they are significant characters of the value.
    i++
  }
```

**Review by jsumners — APPROVED** [review]
Looks good to me with an added comment for clarity.

File: lib/utils.js (hunk 2 above)
Comment (q0rban) [reply lib/utils.js:84]: Happy to add this comment, though I wonder if that means we should delete the comment on line 80.

Comment (q0rban) [reply lib/utils.js:95]: Done.

Comment (jsumners) [reply lib/utils.js:95]: Good job with the docblock. I'd still like to see the `while` loop comment so that we don't have to pretend to be a computer to understand what is going on.

Comment (q0rban) [reply lib/utils.js]: You got it.

**Review by jsumners — APPROVED** [review]
Looks good to me.

**Comment by Eomm** [comment]
I can merge but I can't release

cc @mcollina

**Comment by jsumners** [comment]
Yep. This package is not in the npm org 😕

**Comment by q0rban** [comment]
@Eomm @jsumners any update on this? We've been running a fork in our project, but would be great to have this merged into an actual release. We also have the PR in #88 in our fork.

**Comment by jsumners** [comment]
> @Eomm @jsumners any update on this? We've been running a fork in our project, but would be great to have this merged into an actual release. We also have the PR in #88 in our fork.

There isn't anything I can do. The package isn't in the org, and @mcollina is the only one with access to publish it.
